### ISSUE TITLE
Broken link in Example2-Backlight.ino

### ISSUE THREAD

**Issue by PaulskPt** [sparkfun/SparkFun_SerLCD_Arduino_Library#12]
In the example at:  https://github.com/sparkfun/SparkFun_SerLCD_Arduino_Library/blob/master/examples/Example2-Backlight/Example2-Backlight.ino, line 29, is mentioned the link:
"http://librarymanager/All#SparkFun_SerLCD ".
Using this link results in the error: "ERR_NAME_NOT_RESOLVED".

**Comment by nseidle** [comment]
Works for me. Arduino v1.8.13 on Windows 10. What version of Arduino IDE are you using on what OS?

**Comment by PaulskPt** [comment]
Hi, thank you for the reply. I just tried again in: a) MS Windows 10 Edge; b) Google chrome browser. I get these errors ( the Edge screenshot text is in Portuguese language, but you'll get the notion).
![SerLCD_link_not_accessable](https://user-images.githubusercontent.com/9107950/136855996-1f595817-2426-4628-9c4e-a1d9ab6a0279.png)

![SerLCD_link_not_accessable_img2](https://user-images.githubusercontent.com/9107950/136856280-bb87f014-ba2a-4243-8526-a17b4b3fe664.png)

This problem has nothing to do with which type of Arduino IDE I am using on what OS. It just copied the link from the text in Example 2 and pasted it in each of the two mentioned webbrowsers. Maybe it's a DNS problem.

**Comment by nseidle** [comment]
Oh - that link is not a browser link, it's supposed to be clicked inside the Arduino IDE. The IDE will then open the library mgr window:

![image](https://user-images.githubusercontent.com/117102/136860584-402d71e2-f044-4c99-99d4-014c99f75f1c.png)
