### ISSUE TITLE
Missing return value in SerLCD::write()

### ISSUE THREAD

**Issue by gvansickle** [sparkfun/SparkFun_SerLCD_Arduino_Library#3]
Note the missing return on SerLCD::write(), which should return a size_t but returns nothing:

https://github.com/sparkfun/SparkFun_SerLCD_Arduino_Library/blob/34d4f1dbd32d8c42e6b85679d1ab3aaae0557272/src/SerLCD.cpp#L395

**Comment by fourstix** [comment]
Hi, Good catch.  It's an error in the original code that Sparkfun harvested.  
It should end with "return 1;" since one byte was written.

**Comment by fourstix** [comment]
I have submitted a pull request with a fix.  Thanks for raising this issue.

**Comment by nseidle** [comment]
Thanks all! Will be rolled into next release.
