### ISSUE TITLE
[Constructor]: missing possibility to set base values via contructor

### ISSUE THREAD

**Issue by hasenradball** [sparkfun/SparkFun_SerLCD_Arduino_Library#5]
I am missing the possibility to easily set up the main LCD settings via constructor, like:

// constructor with address, cols, rows
`SerLCD lcd(0x72, 20, 4);`
or
`SerLCD lcd(0x72, 16, 2);`

so this would be great to initialize the display directly with the main settings.

**Comment by nseidle** [comment]
I don't fully understand what you are suggesting, The display width and lines are set at the factory (SparkFun) by the firmware that runs on the actual display, not by this library.

Passing the address in the constructor is fine, but we almost always pass it in the begin function along side the Wire port so I won't be breaking that standard on this library.

**Comment by hasenradball** [comment]
Hi,
ok that sounds fine I didn‘t catch that the cols and rows are set by the firmware.

Cool so my issue is obsolete 😀
